[
    "python",
    "java",
    "javascript",
    "html",
    "css",
    "php",
    "sql",
    "ruby",
    "perl",
    "r",
    "go",
    "swift",
    "kotlin",
    "rust",
    "typescript",
    "bash",
    "powershell",
    "matlab",
    "assembly",
    "vba",
    "visual basic",
    "dart",
    "groovy",
    "scala",
    "history",
    "calculus",
    "the lord of the rings",
    "the hobbit",
    "the silmarillion",
    "the children of hurin",
    "the fall of gondolin",
    "the book of lost tales",
    "the lay of aotrou and itroun",
    "the lay of leithian",
    "the shaping of middle-earth",
    "the lost road and other writings",
    "the return of the shadow",
    "the treason of isengard",
    "the war of the ring",
    "sauron defeated",
    "morgoths ring",
    "the war of the jewels",
    "the peoples of middle-earth",
    "ready player one",
    "Romeo and Juliet by William Shakespeare ",
    "Moby Dick; Or, The Whale by Herman Melville ",
    "A Room with a View by E. M. Forster ",
    "Middlemarch by George Eliot ",
    "Little Women; Or, Meg, Jo, Beth, and Amy by Louisa May Alcott ",
    "The Complete Works of William Shakespeare by William Shakespeare ",
    "The Blue Castle a novel by L. M. Montgomery ",
    "The Enchanted April by Elizabeth Von Arnim ",
    "The Adventures of Ferdinand Count Fathom — Complete by T. Smollett ",
    "Cranford by Elizabeth Cleghorn Gaskell ",
    "The Expedition of Humphry Clinker by T. Smollett ",
    "History of Tom Jones, a Foundling by Henry Fielding ",
    "The Adventures of Roderick Random by T. Smollett ",
    "Twenty Years After by Alexandre Dumas ",
    "My Life — Volume 1 by Richard Wagner ",
    "Pride and Prejudice by Jane Austen ",
    "The Picture of Dorian Gray by Oscar Wilde ",
    "Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley ",
    "Noli Me Tangere by José Rizal ",
    "Alice's Adventures in Wonderland by Lewis Carroll ",
    "Ang Filibusterismo (Karugtóng ng Noli Me Tangere) by José Rizal ",
    "The slang dictionary  by John Camden Hotten ",
    "The Yellow Wallpaper by Charlotte Perkins Gilman ",
    "War and Peace by graf Leo Tolstoy ",
    "Dracula by Bram Stoker ",
    "The Great Gatsby by F. Scott Fitzgerald ",
    "A Tale of Two Cities by Charles Dickens ",
    "The Importance of Being Earnest A Trivial Comedy for Serious People by Oscar Wilde ",
    "The Adventures of Sherlock Holmes by Arthur Conan Doyle ",
    "The Count of Monte Cristo, Illustrated by Alexandre Dumas ",
    "Jane Austen and her works by Sarah Tytler ",
    "The Brothers Karamazov by Fyodor Dostoyevsky ",
    "Metamorphosis by Franz Kafka ",
    "The Terriford mystery by Marie Belloc Lowndes ",
    "Ulysses by James Joyce ",
    "Crime and Punishment by Fyodor Dostoyevsky ",
    "A Doll's House  a play by Henrik Ibsen ",
    "The Romance of Lust A classic Victorian erotic novel by Anonymous ",
    "The Kama Sutra of Vatsyayana by Vatsyayana ",
    "The accomplisht cook by Robert May ",
    "After world's end by Jack Williamson ",
    "The Prince by Niccolò Machiavelli ",
    "Florante at Laura by Francisco Balagtas ",
    "The Reign of Greed by José Rizal ",
    "Grimms' Fairy Tales by Jacob Grimm and Wilhelm Grimm ",
    "Great Expectations by Charles Dickens ",
    "Jane Eyre An Autobiography by Charlotte Brontë ",
    "Tractatus Logico-Philosophicus by Ludwig Wittgenstein ",
    "The Strange Case of Dr. Jekyll and Mr. Hyde by Robert Louis Stevenson ",
    "Lost on Venus by Edgar Rice Burroughs ",
    "Adventures of Huckleberry Finn by Mark Twain ",
    "The Philippines a Century Hence by José Rizal ",
    "The Wonderful Wizard of Oz by L. Frank Baum ",
    "The Iliad by Homer ",
    "Meditations by Emperor of Rome Marcus Aurelius ",
    "A Modest Proposal by Jonathan Swift ",
    "Marcia Schuyler by Grace Livingston Hill ",
    "The story of Eros & Psyche (retold from Apuleius)  by Edward Carpenter ",
    "Don Quixote by Miguel de Cervantes Saavedra ",
    "Beyond Good and Evil by Friedrich Wilhelm Nietzsche ",
    "Darwin by Gamaliel Bradford ",
    "Treasure Island by Robert Louis Stevenson ",
    "The Adventures of Tom Sawyer, Complete by Mark Twain ",
    "Moby Multiple Language Lists of Common Words by Grady Ward ",
    "Gloria  by Emma Dorothy Eliza Nevitte Southworth ",
    "The Scarlet Letter by Nathaniel Hawthorne ",
    "Scream at midnight by Joseph Payne Brennan ",
    "Edith Lyle  by Mary Jane Holmes ",
    "Thus Spake Zarathustra A Book for All and None by Friedrich Wilhelm Nietzsche ",
    "The History of the Decline and Fall of the Roman Empire by Edward Gibbon ",
    "Anne of Green Gables by L. M. Montgomery ",
    "The Prophet by Kahlil Gibran ",
    "Walden, and On The Duty Of Civil Disobedience by Henry David Thoreau ",
    "Overland through Asia; Pictures of Siberian, Chinese, and Tartar Life by Thomas Wallace Knox ",
    "Tarzan at the Earth's core by Edgar Rice Burroughs ",
    "Wuthering Heights by Emily Brontë ",
    "Hand-book on cheese making by Geo. E. Newell ",
    "Peter Pan by J. M. Barrie ",
    "The Odyssey by Homer ",
    "Calculus Made Easy by Silvanus P. Thompson ",
    "Anna Karenina by graf Leo Tolstoy ",
    "The divine comedy by Dante Alighieri ",
    "The Rámáyan of Válmíki, translated into English verse by Valmiki ",
    "Les Misérables by Victor Hugo ",
    "The Tragical History of Doctor Faustus by Christopher Marlowe ",
    "The dramatic instinct in children ",
    "Winnie-the-Pooh by A. A. Milne ",
    "The Republic by Plato ",
    "Emma by Jane Austen ",
    "The War of the Worlds by H. G. Wells ",
    "The Hound of the Baskervilles by Arthur Conan Doyle ",
    "The Time Machine by H. G. Wells ",
    "Little Women by Louisa May Alcott ",
    "The Jungle Book by Rudyard Kipling ",
    "Demonology and Devil-lore by Moncure Daniel Conway ",
    "A Study in Scarlet by Arthur Conan Doyle ",
    "Dubliners by James Joyce ",
    "Siddhartha by Hermann Hesse ",
    "The King in Yellow by Robert W. Chambers ",
    "The King James Version of the Bible",
    "The Hackers Playbook 2",
    "The Hackers Playbook 3",
    "Real-World Bug Hunting",
    "Hacking APIs",
    "RTFM v1",
    "Hacking The Art of Exploitation 2nd Edition",
    "The Web Application Hacker’s Handbook",
    "Penetration Testing A Hands-On Introduction to Hacking",
    "Kali Linux Revealed",
    "Kali Training",
    "Ghost in the Wires",
    "Advanced Penetration Testing",
    "Black Hat Python, 2nd Edition",
    "Hacking mit Metasploit, 3rd Edition",
    "Bug Bounty Bootcamp",
    "Ethical Hacking Courses",
]
